collections:
  facilities:
    output: true
  facilities-preview:
    output: true
  project-main:
    output: true
  project-objectives:
    output: true
  project-workpackages:
    output: true
  project-participants:
    output: true
  press-releases:
    output: true
  leaflets:
    output: true
  news:
    output: true
  deliverables:
    output: true
  conferences:
    output: true
  workshops:
    output: true
  webinars:
    output: true
  innovations:
    output: true
  

defaults:
  - scope:
      path: ""
      type: "project"
    values:
      layout: "base"
  - scope:
      path: ""
      type: "press-releases"
    values:
      layout: "press-release"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: "facilities"
    values:
      layout: "facility"
  - scope:
      path: ""
    values:
      layout: "base"
