collections:
  facilities:
    output: true
  facilities-preview:
    output: true
  authors:
    output: true
  experiments-preview:
    output: true
  experiments:
    output: true
  project-main:
    output: true
  project-objectives:
    output: true
  project-workpackages:
    output: true
  

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"
  - scope:
      path: ""
      type: "project"
    values:
      layout: "base"
  - scope:
      path: ""
      type: "facilities"
    values:
      layout: "facility"
  - scope:
      path: ""
    values:
      layout: "base"
