collections:
  authors:
    output: true
  experiments-preview:
    output: true
  experiments:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"
  - scope:
      path: ""
    values:
      layout: "base"
