name: Jekyll Deployment

on:
  push:
    branches:
      - master
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Specify the Jekyll source location as a parameter
    - uses: helaili/jekyll-action@v2
      with:
        build_only: true
        jekyll_src: 'website'
        target_branch: 'master'
        #target_path: './workspace/website/build'
    
    - name : ls prev
      run : "ls ../"
    - name : ls
      run : "ls ."
    - name : ls website
      run : "ls ./website"

    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r website.zip website/build
        
    - uses: wei/curl@v1
      with:
        args:  -X POST -F 'key="${{ secrets.UPDATE_KEY }}"' -F 'website_zip=@./website.zip' https://www.5gasp.eu/update
